version: '3'
services:
  mysql-db:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: buithienadmin
      MYSQL_DATABASE: videostreaming_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nestjsbackend:latest
    container_name: nestjs-backend-container
    ports:
      - "3009:3009"
    depends_on:
      - mysql-db
    environment:
      MYSQL_HOST: mysql-db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: buithienadmin
      MYSQL_DATABASE: videostreaming_db

volumes:
  mysql-data:
